import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import { useFormik } from 'formik'

// import Form from './components/form'
import Timeline from './components/timeline'

const Home = () => {
  const [data, setData] = useState({})
  const [clickSubmit, setClickSubmit] = useState(false)

  const [table, setTable] = useState([])
  const genders = ['ชาย', 'หญิง']

  const formik = useFormik({
    initialValues: {},
    onSubmit: async (values, { setSubmitting }) => {
      const { datetime, detail } = values;
      console.log(values)
      setData(values)
      setClickSubmit(true)

      table.push({ datetime: datetime, detail: detail })
    }
  });

  return (
    <div className="container">
      <Head>
        <title>Covid Timeline Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossOrigin="anonymous" />
      </Head>

      <div className="py-5 text-center">
        <h1 className="">COVID Timeline Generator</h1>
      </div>
      <div className="row">
        <div className="col-md-5">
          <form
            onSubmit={formik.handleSubmit}
            className="mb-3"
          >
            <div className="card card-body mb-3 text-light" style={{ backgroundColor: '#34577e' }}>
              <h4 className="mb-3">ข้อมูลผู้ป่วย &rarr;</h4>
              <div className="form-group">
                <div className="row mb-3">
                  <div className="col-md-6">
                    <label className="form-label">เพศ</label>
                    <select
                      className="custom-select d-block w-100"
                      onChange={formik.handleChange}
                      name="gender"
                      required
                    >
                      <option value="">เลือกเพศ</option>
                      {genders.map((gender, index) => (
                        <option value={gender} key={index}>
                          {gender}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div className="col-md-6">
                    <label className="form-label">อายุ</label>
                    <input
                      type="number"
                      className="form-control"
                      name="age"
                      onChange={formik.handleChange}
                      required
                    />
                  </div>
                </div>

                <div className="row">
                  <div className="col">
                    <label className="form-label">อาชีพ</label>
                    <input
                      type="text"
                      className="form-control"
                      name="job"
                      onChange={formik.handleChange}
                      required
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className="card card-body text-light" style={{ backgroundColor: '#34577e' }}>
              <h4 className="mb-3">ข้อมูลไทม์ไลน์ &rarr;</h4>
              <div className="row mb-3">
                <div className="col">
                  <label className="form-label">วันเวลา</label>
                  <input
                    type="datetime-local"
                    className="form-control"
                    name="datetime"
                    onChange={formik.handleChange}
                    required
                    />
                </div>
              </div>
              <div className="row mb-3">
                <div className="col">
                  <label className="form-label">รายละเอียด</label>
                  <textarea
                    className="form-control"
                    rows={5}
                    name="detail"
                    onChange={formik.handleChange}
                    required
                  />
                </div>
              </div>
              <div className="row">
                <div className="col">
                  <input
                    type="submit"
                    disabled={formik.isSubmitting}
                    className="btn btn-warning btn-block"
                    value="เพิ่มข้อมูล"
                  />
                </div>
              </div>
            </div>
          </form>
        </div>
        <div className="col-md-7">
          <Timeline
            value={data}
            clickSubmit={clickSubmit}
            table={table}
          />
        </div>
      </div>
    </div>
  )
}

export default Home;