import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Form from './components/form'
import Timeline from './components/timeline'

const Home = () => {
  return (
    <div className="container">
      <Head>
        <title>Covid Timeline Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossOrigin="anonymous" />
      </Head>

      <div className="py-5 text-center">
        <img className="d-block mx-auto mb-4" src="https://getbootstrap.com/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72" />
        <h1 className="">COVID Timeline Generator</h1>
      </div>
      <div className="row">
        <div className="col-md-6">
          <Form />
        </div>
        <div className="col-md-6">
          <Timeline />
        </div>
      </div>
    </div>
  )
}

export default Home;